// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Northwind.EFCore.Data;

namespace Northwind.EFCore.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20210911155859_Supplier")]
    partial class Supplier
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("Northwind.EFCore.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT(11)");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("Description")
                        .HasColumnType("MEDIUMTEXT");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Northwind.EFCore.Models.CustomerDemographics", b =>
                {
                    b.Property<string>("CustomerTypeID")
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("CustomerDesc")
                        .IsRequired()
                        .HasColumnType("MEDIUMTEXT");

                    b.HasKey("CustomerTypeID");

                    b.ToTable("CustomerDemographics");
                });

            modelBuilder.Entity("Northwind.EFCore.Models.Region", b =>
                {
                    b.Property<int>("RegionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT(11)");

                    b.Property<string>("RegionDescription")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("RegionID");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("Northwind.EFCore.Models.Shipper", b =>
                {
                    b.Property<int>("ShipperID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT(11)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(40)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(24)");

                    b.HasKey("ShipperID");

                    b.ToTable("Shippers");
                });

            modelBuilder.Entity("Northwind.EFCore.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT(11)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("VARCHAR(60)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("VARCHAR(40)");

                    b.Property<string>("ContactName")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("ContactTitle")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.Property<string>("Fax")
                        .HasColumnType("VARCHAR(24)");

                    b.Property<string>("HomePage")
                        .HasColumnType("MEDIUMTEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("VARCHAR(24)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("VARCHAR(15)");

                    b.HasKey("SupplierID");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("Northwind.EFCore.Models.Territory", b =>
                {
                    b.Property<string>("TerritoryID")
                        .HasColumnType("VARCHAR(20)");

                    b.Property<int>("RegionID")
                        .HasColumnType("INT(11)");

                    b.Property<string>("TerritoryDescription")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.HasKey("TerritoryID");

                    b.HasIndex("RegionID");

                    b.HasIndex("TerritoryDescription")
                        .IsUnique();

                    b.HasIndex("TerritoryID")
                        .IsUnique();

                    b.ToTable("Territories");
                });

            modelBuilder.Entity("Northwind.EFCore.Models.Territory", b =>
                {
                    b.HasOne("Northwind.EFCore.Models.Region", "Region")
                        .WithMany("Territories")
                        .HasForeignKey("RegionID")
                        .HasConstraintName("FK_Region")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Northwind.EFCore.Models.Region", b =>
                {
                    b.Navigation("Territories");
                });
#pragma warning restore 612, 618
        }
    }
}
